LESSONS = {
    "doji": {"title": "Doji",
        "theory": "Open and close are almost equal, so neither buyers nor sellers won. Traders read it as indecision, and a possible turning point if it follows a strong trend.",
        "conditions": "Matters most after a long run up or down. In a quiet, sideways market it means little."},
    "hammer": {"title": "Hammer",
        "theory": "Sellers pushed the price down during the day, but buyers pushed it back up near the open. The theory says sellers are running out of strength, so a bounce may follow.",
        "conditions": "Only counts after a fall (we require a 5-day decline). In the middle of a rally the same shape is not a hammer."},
    "shooting_star": {"title": "Shooting star",
        "theory": "Buyers pushed the price up, but sellers pushed it back down by the close. The theory says buying strength is fading, so a drop may follow.",
        "conditions": "Only counts after a rise (we require a 5-day gain)."},
    "bull_marubozu": {"title": "Bullish marubozu",
        "theory": "A green candle with almost no wicks: buyers controlled the whole day. Traders read it as strong momentum.",
        "conditions": "Stronger when volume is high. In NEPSE it can also be a day that hit the price limit."},
    "bear_marubozu": {"title": "Bearish marubozu",
        "theory": "A red candle with almost no wicks: sellers controlled the whole day. Traders read it as strong downward momentum.",
        "conditions": "Stronger when volume is high. It can also be a day that hit the lower price limit."},
    "bull_engulfing": {"title": "Bullish engulfing",
        "theory": "A green candle whose body covers the previous red body. Buyers overwhelmed the sellers from the day before, so the trend may turn up.",
        "conditions": "Meant to appear after a downtrend."},
    "bear_engulfing": {"title": "Bearish engulfing",
        "theory": "A red candle whose body covers the previous green body. Sellers overwhelmed the buyers from the day before, so the trend may turn down.",
        "conditions": "Meant to appear after an uptrend."},
    "morning_star": {"title": "Morning star",
        "theory": "Three candles: a long red, a small body, then a green that closes above the first candle's midpoint. Selling fades, then buyers take over.",
        "conditions": "Meant to appear at the end of a downtrend."},
    "evening_star": {"title": "Evening star",
        "theory": "Three candles: a long green, a small body, then a red that closes below the first candle's midpoint. Buying fades, then sellers take over.",
        "conditions": "Meant to appear at the end of an uptrend."},
}